# fly.staging.toml app configuration file for staging deployment
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mage-core-hidden-water-2116'
primary_region = 'bom'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  KB_PROCESSOR_ENABLED = 'true'
  NODE_ENV = 'staging'
  PORT = '3001'
  UPSTASH_REDIS_REST_URL = 'https://rare-tahr-54350.upstash.io'
  STAGING = 'true'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[services]]
  protocol = 'tcp'
  internal_port = 3001
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 500

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048

[[metrics]]
  port = 3001
  path = '/metrics'
  https = false 